config/routes.rb
Rails.application.routes.draw do
  root "taiketsus#index"
  resources :taiketsus, only: [:index, :show, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :abouts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :topic
    has_many :good_counts
    has_many :bad_counts
    validates :text, presence: true
end

app/models/taiketsu.rb
class Taiketsu < ApplicationRecord
  has_many  :topics, dependent: :destroy
  accepts_nested_attributes_for :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to  :taiketsu, optional: true
  has_many :comments, dependent: :destroy
  # 投稿が削除されたときに一緒にコメントも削除する
  validates   :topic,
      presence: true,
      length:   {in: 1 .. 50}
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index
    @taiketsu = Taiketsu.new
    @taiketsu.topics.build
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :basic_auth, if: :production?
    protect_from_forgery with: :exception

    def production?
        Rails.env.production?
    end
  
    private
  
    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
      end
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(text: comment_params[:text], topic_id: comment_params[:topic_id])
        @comment.session_id = session[:session_id]
        if @comment.save
          respond_to do |format|
            format.html { redirect_to taiketsu_path(params[:taiketsu_id]) }
            format.json
          end
        else
          flash.now[:alert] = 'コメントを入力してください'
          redirect_to taiketsu_path(params[:taiketsu_id])
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:text, :topic_id, :taiketsu_id)
    end

end

app/controllers/taiketsus_controller.rb
class TaiketsusController < ApplicationController
    before_action :set_taiketsu, only: [:index, :show]

    def index
# 初期表示
      hash = {}
      keys = []
      @taiketsus = Taiketsu.all
      @taiketsus.each do |taiketsu|
        comments = taiketsu.topics.joins(:comments).group(:topic_id).count
        if comments.values[0].blank? && comments.values[1].blank?
          sum = 0
        elsif comments.values[0].blank?
          sum = comments.values[1]
        elsif comments.values[1].blank?
          sum = comments.values[0]
        else
          sum = comments.values[0] + comments.values[1]
        end
        hash[taiketsu.id] = sum
      end
      @comment_hash = hash.sort_by {| k, v | v}.reverse
      @comment_hash.each do |key|
         keys << key[0]
      end

      @hot_taiketsus = Taiketsu.where(id: @keys).order(['field(id, ?)', @keys]).page(params[:page]).per(12)
      @accepting_taiketsus= Taiketsu.includes(:topics).page(params[:page]).per(6).order("created_at DESC")

      @random = Taiketsu.offset( rand(Taiketsu.count) ).first

      @taiketsu = Taiketsu.new
      @taiketsu.topics.build

# インクリメンタルサーチ
      # topicを検索
      @topics = Topic.where('topic LIKE(?)', "%#{params[:keyword]}%")
      # 配列を作成
      taiketsu_id_array = []
      @array = []
      # 検索したtopicのtaiketsu_idを配列に入れる
      @topics.each do |topic|
        taiketsu_id_array << topic.taiketsu_id
      end
      # 被ったtaiketsu_idを排除
      taiketsu_id_array.uniq!
      # taiketsu_idからtaiketsuレコードを取得し配列に入れる
      taiketsu_id_array.each do |taiketsu_id|
        search_taiketsu = Taiketsu.find(taiketsu_id)
        @array << search_taiketsu
      end
      respond_to do |format|
        format.html
        format.json
      end
    end

    def show
      @url = request.url
      @session = session[:session_id]
      @taiketsus = Taiketsu.new
      @taiketsus.topics.build

      @taiketsu = Taiketsu.find(params[:id])
      @taiketsu_topics = @taiketsu.topics
      @topic_first = @taiketsu_topics.first
      @topic_second = @taiketsu_topics.second

      @comment = Comment.new
      @comments_first = @topic_first.comments
      @comments_second = @topic_second.comments

      @show_taiketsus = Taiketsu.where(id: @keys).order(['field(id, ?)', @keys]).page(params[:page]).per(1)
      @accepting_taiketsus = Taiketsu.includes(:topics).page(params[:page]).per(6).order("created_at DESC")
    end

    def create
      @taiketsu = Taiketsu.new(taiketsu_params)
      session[:expires_at] = 1.day.from_now
      @taiketsu.session_id = session[:session_id]
      if @taiketsu.save
        redirect_to taiketsus_path
      else
        render :show
      end
    end

    def destroy
      @taiketsu = Taiketsu.find(params[:id])
      @taiketsu.destroy
      redirect_to taiketsus_path
    end

  private

    def taiketsu_params
      params.require(:taiketsu).permit(
        topics_attributes: [:topic]
      )
    end

    def set_taiketsu
      hash = {}
      @keys = []
      @taiketsus = Taiketsu.all
      @taiketsus.each do |taiketsu|
        comments = taiketsu.topics.joins(:comments).group(:topic_id).count
        if comments.values[0].blank? && comments.values[1].blank?
          sum = 0
        elsif comments.values[0].blank?
          sum = comments.values[1]
        elsif comments.values[1].blank?
          sum = comments.values[0]
        else
          sum = comments.values[0] + comments.values[1]
        end
        hash[taiketsu.id] = sum
      end
      @comment_arrays = hash.sort_by {| k, v | v}.reverse
      @comment_arrays.each_with_index do |array, index|

        # paramsのidがコメント数でsortした配列のidに一致
        if params[:id].to_i == array[0]
          # 配列が先頭だったら
          if index == 0
            @prev = 0
            @next = @comment_arrays[index+1][0]
          # 配列が最後だったら
          elsif index == @comment_arrays.length - 1
            @prev = @comment_arrays[index-1][0]
            @next = 0
          # それ以外
          else
            @prev = @comment_arrays[index-1][0]
            @next = @comment_arrays[index+1][0]
          end
        end
        @keys << array[0]
      end

    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taiketsus_helper.rb
module TaiketsusHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/abouts/index.html.haml
.about-header
  .about-header__name
    = link_to "タイケツ", root_path, class: "toppage"
.mains
  .main
    .main__top
      %h1.main__top--headline
        タイケツの楽しみ方
      .main__top--image
        %img(src="./images/keyvisual.jpg" alt="タイケツ")
      %h2.main__top--title
        分かり合えない二人、本音をぶつけ合ってみませんか？
      .main__top--sentence
        %p
          営業とエンジニア、デザイナーとコーダー、大阪と東京など、いつも憎しみ合い、分かり合えない関係がこの世界には存在します。
          %br/
          もしかしたらあなたもそんな関係に悩まされている中のひとりかもしれませんね。
        %p
          %strong タイケツ
          はそんな2つのことがらについて、それぞれの立場から主張を投稿できるサービスです。
          %br/
          会員登録やソーシャルアカウントを使う必要はありません。誰にも知られることなく、本音を語ってください。
        %p
          本音をぶつけ合い、お互いを理解し合い、二人が少しでも分かりあえますように…。
    .main__bottom
      %h2.main__bottom--title
        タイケツの使い方
      %h3.main__bottom--what
        お題を探して主張をぶつける
      .main__bottom--image
        %img(src="./images/img.jpg" alt="そば")
      .main__bottom--image__sentence
        %p
          用意されたお題にはそれぞれの立場から主張を投稿することができます。
          %br/
          自分がいかに優れているか、また、相手がいかに劣っているか、遠慮なく主張してください。
          %br/
          本音を聞いてみると、自分の悪いところ、相手のいいところが見えてくるかもしれません。
        %h3.main__bottom--post
          お題を投稿する
        .main__bottom--image
          %img(src="./images/img2.jpg" alt="画像2")/
        .main__bottom--sentence-post
          %p
            私の大好きな○○が□□より人気がないなんてありえない、理解できない、そんな悩みをお持ちなら、一息入れてみんなの意見も聞いてみませんか？
          %p
            2つの関係をお題として投稿し、みんなからの意見を待ってみましょう。
          %h3.main__bottom--delete
            主張・お題を削除する
          .main__bottom--image
            %img(src="./images/img3.jpg" alt="画像3")/
          .main__bottom--image__sentence
            %p
              ちょっと言い過ぎたかな…と思ったら削除ボタンをクリックすることで主張、お題を削除することができます。
            %p
              ブラウザを閉じるとセッション情報がなくなるため削除機能が使えなくなります。
              %br/
              のちほど投稿内容を削除したい場合は管理者までお問い合わせください。
.footer
  = render "shared/footer"
.global-footer
  = render "shared/global-footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaiketsuE
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7", :src => "https://code.jquery.com/jquery-3.1.1.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}
    %script{:src => "https://code.jquery.com/jquery-3.2.1.min.js"}
    %script{:src => "http://code.jquery.com/color/jquery.color-2.1.2.min.js"}

  %body
    = yield

app/views/shared/_footer.html.haml
.footer
    .footer__title
        お題を投稿する
    .footer__sentence
        ライバル関係にある2つのことがらを投稿してみてください。
    = form_for @taiketsu do |f|
        .footer__form
            .footer__form--input
                - 2.times do |i|
                    = f.fields_for :topics do |topic|
                        .footer__form--input__text
                            = topic.text_field :topic, maxlength: "50", class: "form"
                    - if i == 0
                        .footer__form--input__VS
                            VS
            .footer__form--btn
                = f.submit "投稿する", class: "btn"
            .footer__form--sentence
                ＊投稿できるお題は各50文字以内ですよ

app/views/shared/_global-footer.html.haml
.global-footer
    %ul.global-footer__contents
        %li.list
            = link_to "トップページ", root_path, class: "link"
        %li.list
            = link_to "タイケツの楽しみ方", abouts_path, class: "link"
        %li.list
            = link_to "利用規約・免責", root_path, class: "link"
        %li.list
            = link_to "お問い合わせ", root_path, class: "link"
    .global-footer__right
        ©️TAIKETSU

app/views/shared/_looking-opinion.html.haml
.main__name--bottom
  - if (@url == "/taiketsus\/\d+\/")
    .wanted_title.color-w
      ご意見募集中のお題
  - else
    .wanted_title
      ご意見募集中のお題
- @accepting_taiketsus.each_slice(3) do |accepting_taiketsus|
  .main__posts
    - accepting_taiketsus.each do |accepting_taiketsu|
      .main__posts--list
        = link_to taiketsu_path(accepting_taiketsu.id), class: "link" do
          .main__posts--list__title
            = accepting_taiketsu.topics.first.topic
          .VS
            VS
          .main__posts--list__title
            = accepting_taiketsu.topics.second.topic
          .main__posts--list__vote
            .main__posts--list__vote--left
              = accepting_taiketsu.topics.first.comments.count
            .main__posts--list__vote--right
              = accepting_taiketsu.topics.second.comments.count

app/views/shared/_main.html.haml
.main
  .main__name--top
    .popular_title
      人気のお題

    - @hot_taiketsus.each_slice(3) do |hot_taiketsus|
      .main__posts
        - hot_taiketsus.each do |hot_taiketsu|
          .main__posts--list
            = link_to taiketsu_path(hot_taiketsu.id), class: "link" do
              .main__posts--list__title
                = hot_taiketsu.topics.first.topic
              .VS
                VS
              .main__posts--list__title
                = hot_taiketsu.topics.second.topic
              .main__posts--list__vote
                .main__posts--list__vote--left
                  = hot_taiketsu.topics.first.comments.count
                .main__posts--list__vote--right
                  = hot_taiketsu.topics.second.comments.count

  .kaminari
    = paginate @hot_taiketsus
  = render "shared/looking-opinion"

  .ran-button#openModal{ :title => "おすすめ" }
    .ran-text
      オススメタイケツ

/* モーダルウィンドウ */
%section#modalArea.modalArea
  #modalBg.modalBg
    .modalWrapper
      .random__subject
        .random__subject-title
          おすすめのタイケツ
        / #closeModel.closeModel
        /   ×
      .random__main__posts--list
        = link_to taiketsu_path(@random.id), class: "link" do
          .random__main__posts--list__title.bgc-red
            .random__topic
              = @random.topics.first.topic
          .random__vs
            VS
          .random__main__posts--list__title.bgc-blue
            .random__topic
              = @random.topics.second.topic
      .random__footer
        さっそく 「 タイケツ 」 してみよう！！

app/views/showpage/_adjustlink.html.haml
.row.adjustlink
  .columns.large-6.small-12.text-left
    - if @prev != 0
      = link_to taiketsu_path(@prev) do
        .fa.fa-arrow-circle-left
          より人気のお題へ
  .columns.large-6.small-12.text-right
    - if @next != 0
      = link_to taiketsu_path(@next) do
        .fa.fa-arrow-circle-right
          より不人気なお題へ

app/views/showpage/_comment_primary.html.haml
.columns.large-6.comment_primary
  .panel.left
    .row
      .columns.large-12
        %h3
          %span.first
            = @topic_first.topic
          からのご意見
        .scroll
          = fa_icon 'arrow-circle-down', class: 'icon-left', title: '意見投稿フォームまでスクロールする'
    - @comments_first.each_with_index do |comment, i|
      - if i % 2 == 0
        .comment_block.bgc-gray
          .row
            .columns.large-12
              %p
                = comment.text
      - else
        .comment_block.bgc-white
          .row
            .columns.large-12
              %p
                = comment.text
    = form_for [@taiketsu, @comment] do |f|
      .comment_form
        .form__input
          = f.text_area :text, placeholder: '思いの丈をぶつけてください', value: "", class: 'new_comment', maxlength: "200", size: "50"
          = f.hidden_field :topic_id, value: @topic_first.id
        .form__submit
          = f.submit value: '意見を投稿する', class: 'submit'
          .form__jump
            = fa_icon 'arrow-circle-up',class: 'jump_icon',title: '上にスクロールする'

app/views/showpage/_comment_secondary.html.haml
.columns.large-6.comment_secondary
  .panel.addhtml.right
    .row
      .columns.large-12
        %h3
          %span.second
            = @topic_second.topic
          からのご意見
        .scroll
          = fa_icon 'arrow-circle-down', class: 'icon-right', title: '意見投稿フォームまでスクロールする'
    - @comments_second.each_with_index do |comment, i|
      - if i % 2 == 0
        .comment_block.bgc-gray
          .row
            .columns.large-12
              %p
                = comment.text
      - else
        .comment_block.bgc-white
          .row
            .columns.large-12
              %p
                = comment.text
    = form_for [@taiketsu, @comment] do |f|
      .comment_form
        .form__input
          = f.text_area :text, placeholder: '思いの丈をぶつけてください', value: "", class: 'new_comment', maxlength: "200", size: "50"
          = f.hidden_field :topic_id, value: @topic_second.id
        .form__submit
          = f.submit value: '意見を投稿する', class: 'submit'
          .form__jump
            = fa_icon 'arrow-circle-up',class: 'jump_icon', title: '上にスクロールする'

app/views/showpage/_header.html.haml
.about-header
  .about-header__name
    %h1
      = link_to "タイケツ", root_path, class: "toppage"

app/views/showpage/_show_footer.html.haml
.footer
    .footer__title
        お題を投稿する
    .footer__sentence
        ライバル関係にある2つのことがらを投稿してみてください。
    = form_for @taiketsus do |f|
        .footer__form
            .footer__form--input
                - 2.times do |i|
                    = f.fields_for :topics do |topic|
                        .footer__form--input__text
                            = topic.text_field :topic, maxlength: "50", class: "form"
                    - if i == 0
                        .footer__form--input__VS
                            VS
            .footer__form--btn
                = f.submit "投稿する", class: "btn"
            .footer__form--sentence
                ＊投稿できるお題は各50文字以内ですよ

app/views/showpage/_top_article.html.haml
.row.top_article
  .columns.large-12.text-center.top_article
    .panel
      .row
        .columns.large-5
          .top_article_cast
            = @taiketsu.topics.first.topic
        .columns.top_article_vs_wrap
          .top_article_vs
            vs
        .columns.large-5.large-offset-2
          .top_article_cast
            = @taiketsu.topics.second.topic
      .row.social
        .column.large-8.text-left
        .column.large-4.text-right
          -if @session == @taiketsu.session_id
            = link_to taiketsu_path(@taiketsu.id), method: :delete, class: "delete_link" do
              = fa_icon "trash", class: "trash_icon", title: "このtaiketsuを削除する"

app/views/taiketsus/index.html.haml
.wraper
  = render "showpage/header"
  = render "toppage/header"
  = render "shared/main"
  = render "shared/footer", topic: @topic
  = render "shared/global-footer"

app/views/taiketsus/show.html.haml
%html
  %body
    %main
      .show-main__bgc
        .left-bg
          .left-count{:hidden => ""}
            = @topic_first.comments.count
        .right-bg
          .right-count{:hidden => ""}
            = @topic_second.comments.count
      = render 'showpage/header'
      = render 'showpage/adjustlink'
      = render 'showpage/top_article'
      .row.singlshowpage
        = render 'showpage/comment_primary'
        = render 'showpage/comment_secondary'
      .row
        .columns.large-12.text-center
          .small
            投稿できるご意見は200文字以内です。
      = render 'shared/looking-opinion'
      = render 'showpage/show_footer'
      = render 'shared/global-footer'

app/views/toppage/_header.html.haml
.header
  .header__top
    %h1.header__top--name
      = link_to "タイケツ", root_path, class: "toppage"
  .header__middle
    %p.header__middle--sentence
      いつも宿敵、ライバルとして憎み合い、争い合う二人。
      %br/
      たまには言いたいことを遠慮なく吐き出してみませんか？
    %ul.header__middle--button
      %li.header__middle--button__list
        = link_to "もっと詳しく", abouts_path, class: "btn"
      %li.header__middle--button__list
        %input.btn1{type: "button", value: "タイケツモード"}

  .header__bottom1
    %ul.header__bottom--links
      %li.list
        = link_to "https://www.facebook.com/", target: "_blank" do
          = fa_icon "facebook", class: "icon"
      %li.list
        = link_to "https://twitter.com/", target: "_blank" do
          = fa_icon "twitter", class: "icon"
      %li.list
        = link_to "http://b.hatena.ne.jp/", target: "_blank" do
          = fa_icon "bold", class: "icon"

  .header__search
    .header__search--title
      お題を検索する
    .header__search--form
      %input#topic-search-field.search__input{:type => "text"}/
      .icon
        %i.fa.fa-search{class: "search_icon", "aria-hidden" => "true"}